openapi: 3.1.0
x-stoplight:
  id: d5k880vbrkfld
info:
  title: sample
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/users/{userId}':
    parameters:
      - schema:
          type: integer
        name: userId
        in: path
        required: true
        description: Id of an existing user.
    get:
      summary: Get User Info by User ID
      tags: []
      responses:
        '200':
          description: User Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Get User Alice Smith:
                  value:
                    id: 142
                    firstName: Alice
                    lastName: Smith
                    email: alice.smith@gmail.com
                    dateOfBirth: '1997-10-31'
                    emailVerified: true
                    signUpDate: '2019-08-24'
        '404':
          description: User Not Found
      operationId: get-users-userId
      description: Retrieve the information of the user with the matching user ID.
    patch:
      summary: Update User Information
      operationId: patch-users-userId
      responses:
        '200':
          description: User Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Updated User Rebecca Baker:
                  value:
                    id: 13
                    firstName: Rebecca
                    lastName: Baker
                    email: rebecca@gmail.com
                    dateOfBirth: '1985-10-02'
                    emailVerified: false
                    createDate: '2019-08-24'
        '404':
          description: User Not Found
        '409':
          description: Email Already Taken
      description: Update the information of an existing user.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                  description: 'If a new email is given, the user''s email verified property will be set to false.'
                dateOfBirth:
                  type: string
            examples:
              Update First Name:
                value:
                  firstName: Rebecca
              Update Email:
                value:
                  email: rebecca@gmail.com
              Update Last Name & Date of Birth:
                value:
                  lastName: Baker
                  dateOfBirth: '1985-10-02'
        description: Patch user properties to update.
  /user:
    post:
      summary: Create New User
      operationId: post-user
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                New User Bob Fellow:
                  value:
                    id: 12
                    firstName: Bob
                    lastName: Fellow
                    email: bob.fellow@gmail.com
                    dateOfBirth: '1996-08-24'
                    emailVerified: false
                    createDate: '2020-11-18'
        '400':
          description: Missing Required Information
        '409':
          description: Email Already Taken
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                dateOfBirth:
                  type: string
                  format: date
              required:
                - firstName
                - lastName
                - email
                - dateOfBirth
            examples:
              Create User Bob Fellow:
                value:
                  firstName: Bob
                  lastName: Fellow
                  email: bob.fellow@gmail.com
                  dateOfBirth: '1996-08-24'
        description: Post the necessary fields for the API to create a new user.
      description: Create a new user.
  /users:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
                  x-stoplight:
                    id: q3doj0itxu4ay
              examples:
                Example 1:
                  value:
                    - id: 1
                      firstName: 拓巳
                      lastName: 高橋
                      email: takahashi.takumi@gmail.com
                      dateOfBirth: '1989-01-11'
                      emailVerified: true
                      createDate: '2023-12-01'
                      referralCount: 23
                      preferredWorkLocation: 大阪府
                      applicationCount: 11
                      progress: 4
                      priority: 1
                      personInCharge: 赤井 大輔
                      updatedAt: '2024-01-12'
                    - id: 2
                      firstName: 花道
                      lastName: 桜木
                      email: hanamichi.sakuragi@gmail.com
                      dateOfBirth: '1982-12-24'
                      emailVerified: true
                      createDate: '2024-01-23'
                      referralCount: 1
                      preferredWorkLocation: 沖縄県
                      applicationCount: 4
                      progress: 2
                      priority: 2
                      personInCharge: 砂川 大地
                      updatedAt: '2024-01-13'
      operationId: get-users
    parameters: []
components:
  schemas:
    User:
      title: User
      type: object
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
        createDate:
          type: string
          format: date
          description: The date that the user was created.
        referralCount:
          type: integer
          x-stoplight:
            id: ctfy6h643qmgp
          default: 0
        preferredWorkLocation:
          type: string
          x-stoplight:
            id: l06bpoyyizpyz
        applicationCount:
          type: integer
          x-stoplight:
            id: 6sc4iqd6lrfbg
          default: 0
        progress:
          type: integer
          x-stoplight:
            id: 7e3l5rv7s66q7
          default: 1
        priority:
          type: integer
          x-stoplight:
            id: p2sve7amfuvww
          default: 1
        personInCharge:
          type: string
          x-stoplight:
            id: ufwd499kydwbl
        updatedAt:
          type: string
          x-stoplight:
            id: jnxe0an5jlzd8
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
        - referralCount
        - applicationCount
        - progress
        - priority
